CREATE DATABASE IF NOT EXISTS hw_database;

CREATE TABLE IF NOT EXISTS cities(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    population BIGINT NOT NULL,
    area FLOAT NOT NULL,
    density FLOAT NOT NULL
);